SPEED:
  Item: redstone
  SpeedBoost: 1
  Haste: 1
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

MOON:
  Item: feather
  JumpBoost: 2
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

SCUBA:
  Item: sugar_cane
  ScubaTime: 10
  Haste: 2
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

LAVA:
  Item: magma_cream
  LavaTime: 2
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

RAGE:
  Item: blaze_rod
  LightningDamage: 5
  FireTime: 4
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

PEACE:
  Item: nether_wart
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

ASSASSIN:
  Item: ender_pearl
  SneakDamage: 4
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

CREEPER:
  Item: gunpowder
  ExplosionSize: 5
  BlockDamage: true
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

SPIDER:
  Item: slime_ball
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

VAMPIRE:
  Item: ghast_tear
  Percent: 25
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite

MINER:
  Item: gold_ingot
  Haste: 1
  ArmorTypes:
    - leather
    - iron
    - gold
    - chainmail
    - diamond
    - pumpkin
    - skull
    - elytra
    - turtle
    - netherite
